export const strings = {
  en: {
    siteName: "Motamot",
    tagline: "Opinion • মতামত",
    hero: "Share your opinion",
    heroSub: "A space for honest voices — in English and Bangla.",
    writeOpinion: "Write an Opinion",
    featured: "Featured",
    hot: "Hot Today",
    allPosts: "All Posts",
    showMore: "Show More",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    loading: "Loading…",
    noPostsYet: "No posts yet. Be the first!",
    postType_problem: "Problem (seeking solution)",
    postType_sharing: "Sharing (just sharing)",
    upvote: "Upvote",
    downvote: "Downvote",
    translate: "Translate",
    translateTo_bn: "Translate to বাংলা",
    translateTo_en: "Translate to English",
    saveTranslation: "Save translation",
    autoTranslated: "Automatically translated",
    comment: "Comment",
    comments: "Comments",
    reply: "Reply",
    report: "Report",
    share: "Share",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    submit: "Submit",
    post: "Post",
    posting: "Posting…",
    postTitle: "Heading",
    postBody: "Your opinion",
    selectLanguage: "Language you wrote in",
    selectType: "Opinion type",
    profanityError:
      "Your post contains disallowed language and cannot be published.",
    loginRequired: "You must be signed in to do this.",
    adminPanel: "Admin Panel",
    flaggedPosts: "Flagged Posts",
    reportedContent: "Reported Content",
    unpublish: "Unpublish",
    approve: "Approve",
    anonymous: "Anonymous",
    by: "by",
    votes: "votes",
    language_en: "English",
    language_bn: "বাংলা",
    problem: "Problem",
    sharing: "Sharing",
    publishedAt: "Published",
    searchPlaceholder: "Search opinions…",
    reportReason: "Reason for report",
    reportSubmitted: "Report submitted. Thank you.",
    ownPostVoteError: "You cannot vote on your own post.",
  },
  bn: {
    siteName: "মতামত",
    tagline: "Opinion • মতামত",
    hero: "মতামত শেয়ার করুন",
    heroSub: "সৎ কণ্ঠস্বরের জায়গা — বাংলা ও ইংরেজিতে।",
    writeOpinion: "মতামত লিখুন",
    featured: "বিশেষ",
    hot: "আজকের আলোচিত",
    allPosts: "সব পোস্ট",
    showMore: "আরো দেখুন",
    signIn: "সাইন ইন",
    signOut: "সাইন আউট",
    signUp: "নিবন্ধন করুন",
    loading: "লোড হচ্ছে…",
    noPostsYet: "এখনো কোনো পোস্ট নেই। প্রথম হন!",
    postType_problem: "সমস্যা (সমাধান চাইছি)",
    postType_sharing: "শেয়ার করছি",
    upvote: "উপভোট",
    downvote: "ডাউনভোট",
    translate: "অনুবাদ করুন",
    translateTo_bn: "বাংলায় অনুবাদ করুন",
    translateTo_en: "ইংরেজিতে অনুবাদ করুন",
    saveTranslation: "অনুবাদ সংরক্ষণ করুন",
    autoTranslated: "স্বয়ংক্রিয়ভাবে অনুবাদিত",
    comment: "মন্তব্য",
    comments: "মন্তব্যসমূহ",
    reply: "উত্তর দিন",
    report: "রিপোর্ট করুন",
    share: "শেয়ার",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    cancel: "বাতিল",
    submit: "জমা দিন",
    post: "পোস্ট করুন",
    posting: "পোস্ট হচ্ছে…",
    postTitle: "শিরোনাম",
    postBody: "আপনার মতামত",
    selectLanguage: "আপনি কোন ভাষায় লিখলেন",
    selectType: "মতামতের ধরন",
    profanityError:
      "আপনার পোস্টে নিষিদ্ধ ভাষা আছে, এটি প্রকাশ করা যাবে না।",
    loginRequired: "এটি করতে আপনাকে সাইন ইন করতে হবে।",
    adminPanel: "অ্যাডমিন প্যানেল",
    flaggedPosts: "ফ্ল্যাগ করা পোস্ট",
    reportedContent: "রিপোর্ট করা কন্টেন্ট",
    unpublish: "প্রকাশ বন্ধ করুন",
    approve: "অনুমোদন করুন",
    anonymous: "অজ্ঞাতনামা",
    by: "লেখক",
    votes: "ভোট",
    language_en: "English",
    language_bn: "বাংলা",
    problem: "সমস্যা",
    sharing: "শেয়ারিং",
    publishedAt: "প্রকাশিত",
    searchPlaceholder: "মতামত খুঁজুন…",
    reportReason: "রিপোর্টের কারণ",
    reportSubmitted: "রিপোর্ট জমা দেওয়া হয়েছে। ধন্যবাদ।",
    ownPostVoteError: "আপনি নিজের পোস্টে ভোট দিতে পারবেন না।",
  },
} as const;

export type Lang = keyof typeof strings;
export type StringKey = keyof typeof strings.en;
